incluir_calibres <- function(x){
  case_when(
    stringr::str_detect(x, regex_calibres$regex[1])  ~ regex_calibres$CALIBRE_ARMA_V2[1],
    stringr::str_detect(x, regex_calibres$regex[2])  ~ regex_calibres$CALIBRE_ARMA_V2[2],
    stringr::str_detect(x, regex_calibres$regex[3])  ~ regex_calibres$CALIBRE_ARMA_V2[3],
    stringr::str_detect(x, regex_calibres$regex[4])  ~ regex_calibres$CALIBRE_ARMA_V2[4],
    stringr::str_detect(x, regex_calibres$regex[5])  ~ regex_calibres$CALIBRE_ARMA_V2[5],
    stringr::str_detect(x, regex_calibres$regex[6])  ~ regex_calibres$CALIBRE_ARMA_V2[6],
    stringr::str_detect(x, regex_calibres$regex[7])  ~ regex_calibres$CALIBRE_ARMA_V2[7],
    stringr::str_detect(x, regex_calibres$regex[8])  ~ regex_calibres$CALIBRE_ARMA_V2[8],
    stringr::str_detect(x, regex_calibres$regex[9])  ~ regex_calibres$CALIBRE_ARMA_V2[9],
    stringr::str_detect(x, regex_calibres$regex[10]) ~ regex_calibres$CALIBRE_ARMA_V2[10],
    stringr::str_detect(x, regex_calibres$regex[11]) ~ regex_calibres$CALIBRE_ARMA_V2[11],
    stringr::str_detect(x, regex_calibres$regex[12]) ~ regex_calibres$CALIBRE_ARMA_V2[12],
    stringr::str_detect(x, regex_calibres$regex[13]) ~ regex_calibres$CALIBRE_ARMA_V2[13],
    stringr::str_detect(x, regex_calibres$regex[14]) ~ regex_calibres$CALIBRE_ARMA_V2[14],
    stringr::str_detect(x, regex_calibres$regex[15]) ~ regex_calibres$CALIBRE_ARMA_V2[15],
    stringr::str_detect(x, regex_calibres$regex[16]) ~ regex_calibres$CALIBRE_ARMA_V2[16],
    stringr::str_detect(x, regex_calibres$regex[17]) ~ regex_calibres$CALIBRE_ARMA_V2[17],
    stringr::str_detect(x, regex_calibres$regex[18]) ~ regex_calibres$CALIBRE_ARMA_V2[18],
    stringr::str_detect(x, regex_calibres$regex[19]) ~ regex_calibres$CALIBRE_ARMA_V2[19],
    stringr::str_detect(x, regex_calibres$regex[20]) ~ regex_calibres$CALIBRE_ARMA_V2[20],
    stringr::str_detect(x, regex_calibres$regex[21]) ~ regex_calibres$CALIBRE_ARMA_V2[21],
    stringr::str_detect(x, regex_calibres$regex[22]) ~ regex_calibres$CALIBRE_ARMA_V2[22],
    stringr::str_detect(x, regex_calibres$regex[23]) ~ regex_calibres$CALIBRE_ARMA_V2[23],
    stringr::str_detect(x, regex_calibres$regex[24]) ~ regex_calibres$CALIBRE_ARMA_V2[24],
    stringr::str_detect(x, regex_calibres$regex[25]) ~ regex_calibres$CALIBRE_ARMA_V2[25],
    stringr::str_detect(x, regex_calibres$regex[26]) ~ regex_calibres$CALIBRE_ARMA_V2[26],
    stringr::str_detect(x, regex_calibres$regex[27]) ~ regex_calibres$CALIBRE_ARMA_V2[27],
    stringr::str_detect(x, regex_calibres$regex[28]) ~ regex_calibres$CALIBRE_ARMA_V2[28],
    stringr::str_detect(x, regex_calibres$regex[29]) ~ regex_calibres$CALIBRE_ARMA_V2[29],
    stringr::str_detect(x, regex_calibres$regex[30]) ~ regex_calibres$CALIBRE_ARMA_V2[30],
    stringr::str_detect(x, regex_calibres$regex[31]) ~ regex_calibres$CALIBRE_ARMA_V2[31],
    stringr::str_detect(x, regex_calibres$regex[32]) ~ regex_calibres$CALIBRE_ARMA_V2[32],
    stringr::str_detect(x, regex_calibres$regex[33]) ~ regex_calibres$CALIBRE_ARMA_V2[33],
    stringr::str_detect(x, regex_calibres$regex[34]) ~ regex_calibres$CALIBRE_ARMA_V2[34],
    stringr::str_detect(x, regex_calibres$regex[35]) ~ regex_calibres$CALIBRE_ARMA_V2[35],
    stringr::str_detect(x, regex_calibres$regex[36]) ~ regex_calibres$CALIBRE_ARMA_V2[36],
    stringr::str_detect(x, regex_calibres$regex[37]) ~ regex_calibres$CALIBRE_ARMA_V2[37],
    stringr::str_detect(x, regex_calibres$regex[38]) ~ regex_calibres$CALIBRE_ARMA_V2[38],
    stringr::str_detect(x, regex_calibres$regex[39]) ~ regex_calibres$CALIBRE_ARMA_V2[39],
    stringr::str_detect(x, regex_calibres$regex[40]) ~ regex_calibres$CALIBRE_ARMA_V2[40],
    stringr::str_detect(x, regex_calibres$regex[41]) ~ regex_calibres$CALIBRE_ARMA_V2[41],
    stringr::str_detect(x, regex_calibres$regex[42]) ~ regex_calibres$CALIBRE_ARMA_V2[42],
    stringr::str_detect(x, regex_calibres$regex[43]) ~ regex_calibres$CALIBRE_ARMA_V2[43],
    stringr::str_detect(x, regex_calibres$regex[44]) ~ regex_calibres$CALIBRE_ARMA_V2[44],
    stringr::str_detect(x, regex_calibres$regex[45]) ~ regex_calibres$CALIBRE_ARMA_V2[45],
    TRUE ~ NA_character_
  )
}
